Vagrant.configure("2") do |config|
  # Usar box que tingueu vosaltres
  config.vm.box = "generic/ubuntu1804"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  # Normalment no cal pq ja està configurat
  config.vm.synced_folder ".", "/vagrant"
  config.vm.synced_folder ".\\web", "/opt/vagrantsite"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update 
    sudo apt install -y apache2 #-y = yes
    sudo hostname set-hostname webserver  
    ln -fs /vagrant/web/ /var/www/html/
  SHELL
end
